version: '3.7'

services:

  apigw:
    build:
      context: .
      dockerfile: TrackMyStuff.ApiGateway/Dockerfile
    depends_on:
      - mysqldata
      - rabbitmq
      - seq
    environment:
      - ConnectionStrings__ApiConnection=${API_CONNECTION_STRING}
      - RabbitMq__Hostnames__0=${RABBITMQ_HOST}
      - RabbitMq__Port=${RABBITMQ_PORT}
      - RabbitMq__Username=${RABBITMQ_DEFAULT_USER}
      - RabbitMq__Password=${RABBITMQ_DEFAULT_PASS}
      - Serilog__SeqServerUrl=${SEQ_SERVER_URL}
    ports:
      - "${APIGW_PORT:-5000}:80"

  devsrv:
    build:
      context: .
      dockerfile: TrackMyStuff.DevicesService/Dockerfile
    depends_on:
      - mysqldata
      - rabbitmq
      - seq
    environment:
      - ConnectionStrings__DevConnection=${DEV_CONNECTION_STRING}
      - RabbitMq__Hostnames__0=${RABBITMQ_HOST}
      - RabbitMq__Port=${RABBITMQ_PORT}
      - RabbitMq__Username=${RABBITMQ_DEFAULT_USER}
      - RabbitMq__Password=${RABBITMQ_DEFAULT_PASS}
      - Serilog__SeqServerUrl=${SEQ_SERVER_URL}

  mysqldata:
    image: mariadb:latest
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    ports:
      - "${MYSQL_PORT}:3306"
    volumes:
      - trackmystuff-mysqldata:/var/lib/mysql

  rabbitmq:
    image: rabbitmq:management
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_DEFAULT_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_DEFAULT_PASS}
    ports:
      - "${RABBITMQ_PORT}:5672"
      - "${RABBITMQ_MGMT_PORT}:15672"

  seq:
    image: datalust/seq:latest
    environment:
      - ACCEPT_EULA=Y
    ports:
      - "${SEQ_PORT}:80"

volumes:

  trackmystuff-mysqldata:
    external: false